config/routes.rb
Memes::Application.routes.draw do
  root :to => "home#index"
  match "terms" => "terms#index"
  match "documents" => "documents#index"

end

app/models/term.rb
class Term < ActiveRecord::Base
  has_many :postings, :dependent => :destroy
end

app/controllers/terms_controller.rb
class TermsController < ApplicationController
  # GET /terms
  # GET /terms.json
  def index
    sort = params[:sort] || "freq"
    
    @terms = Term.order(sort + ' DESC').limit(100)
    # @terms = Term.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @terms }
    end
  end

  # GET /terms/1
  # GET /terms/1.json
  def show
    @term = Term.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @term }
    end
  end

  # GET /terms/new
  # GET /terms/new.json
  def new
    @term = Term.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @term }
    end
  end

  # GET /terms/1/edit
  def edit
    @term = Term.find(params[:id])
  end

  # POST /terms
  # POST /terms.json
  def create
    @term = Term.new(params[:term])

    respond_to do |format|
      if @term.save
        format.html { redirect_to @term, notice: 'Term was successfully created.' }
        format.json { render json: @term, status: :created, location: @term }
      else
        format.html { render action: "new" }
        format.json { render json: @term.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /terms/1
  # PUT /terms/1.json
  def update
    @term = Term.find(params[:id])

    respond_to do |format|
      if @term.update_attributes(params[:term])
        format.html { redirect_to @term, notice: 'Term was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @term.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /terms/1
  # DELETE /terms/1.json
  def destroy
    @term = Term.find(params[:id])
    @term.destroy

    respond_to do |format|
      format.html { redirect_to terms_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/views/terms/_form.html.erb
<%= form_for(@term) do |f| %>
  <% if @term.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@term.errors.count, "error") %> prohibited this term from being saved:</h2>

      <ul>
      <% @term.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :term %><br />
    <%= f.text_field :term %>
  </div>
  <div class="field">
    <%= f.label :doc_freq %><br />
    <%= f.number_field :doc_freq %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/terms/edit.html.erb
<h1>Editing term</h1>

<%= render 'form' %>

<%= link_to 'Show', @term %> |
<%= link_to 'Back', terms_path %>

app/views/terms/index.html.erb
<h1>Listing terms</h1>

<dl>
  <dt>Documents</dt>
  <dd><%= Document.count %></dd>
  
  <dt>Number of Distinct Terms</dt>
  <dd><%= Term.count %></dd>

  <dt>Number of Postings</dt>
  <dd><%= Posting.count %></dd>
  
  <dt>Number of Tokens</dt>
  <dd><%= terms = Position.count %></dd>
</dl>
  

<table>
  <tr>
    <th>Rank</th>
    <th>Term</th>
    <th>Absolute<br/>Frequency</th>
    <th>Relative<br/>Frequency</th>
    <th>Document<br/>Frequency</th>
    <th>Stopword</th>
  </tr>

<% @terms.each_with_index do |term, i| %>
  <tr>
    <td><%= i + 1 %></td>
    <td><%= term.term %></td>
    <td><%= term.freq %></td>
    <td><%= number_to_percentage( 100 * term.freq.to_f / terms) %></td>
    <td><%= term.doc_freq %></td>
    <td><%= term.stopword ? "Yes" : "" %></td>
  </tr>
<% end %>
</table>

app/views/terms/new.html.erb
<h1>New term</h1>

<%= render 'form' %>

<%= link_to 'Back', terms_path %>

app/views/terms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Term:</b>
  <%= @term.term %>
</p>

<p>
  <b>Doc freq:</b>
  <%= @term.doc_freq %>
</p>


<%= link_to 'Edit', edit_term_path(@term) %> |
<%= link_to 'Back', terms_path %>